In [1]:
import pandas as pd 
import numpy as np

In [2]:
df = pd.read_excel(r"C:\Users\Siddhesh J. Metkar\Downloads\BTP Phase 2 dataset\Region 1\MCF-7.xlsx")

In [3]:
df

loc1  loc2  loc3  loc4  loc5  loc6  loc7
0      1     1     1     1     1     0     1
1      1     1     1     1     1     1     1
2      1     1     1     1     1     0     0
3      1     1     1     1     1     0     1
4      1     1     1     1     1     1     0
5      1     1     1     1     1     1     1
6      0     0     0     0     0     0     0
7      1     1     1     1     1     0     0
8      1     1     1     1     1     0     1
9      1     1     1     1     1     0     0
10     1     1     1     1     1     0     1
11     1     1     1     1     1     1     0

In [4]:
df2 = pd.read_excel(r"C:\Users\Siddhesh J. Metkar\Downloads\BTP Phase 2 dataset\Region 1\MDA-MB-453.xlsx")

In [5]:
df2

loc1  loc2  loc3  loc4  loc5  loc6  loc7
0      1     0     1     1     1     0     1
1      1     1     1     1     1     1     0
2      1     1     1     1     1     0     0
3      1     1     1     1     1     1     1
4      0     0     1     1     1     1     0
5      1     1     1     1     1     1     1
6      1     1     1     1     1     1     1
7      1     0     1     1     1     0     1
8      1     1     1     1     1     0     1
9      1     0     1     1     1     1     1
10     1     0     1     1     1     0     1
11     1     1     1     1     1     0     0

In [6]:
df3 = pd.read_excel(r"C:\Users\Siddhesh J. Metkar\Downloads\BTP Phase 2 dataset\Region 1\MDA-MB-231.xlsx")

In [7]:
df3

loc1  loc2  loc3  loc4  loc5  loc6  loc7
0      1     1     1     0     1     0     1
1      1     0     1     0     0     1     1
2      1     0     1     1     1     0     1
3      1     0     1     1     1     0     1
4      1     1     1     1     1     0     1
5      1     0     1     1     1     0     1
6      1     0     1     1     1     0     1
7      1     0     1     0     1     1     1
8      1     1     1     1     1     0     0
9      1     0     1     1     1     0     1
10     1     0     0     1     1     1     1
11     1     0     1     1     1     0     1

In [8]:
df4=pd.read_excel(r"C:\Users\Siddhesh J. Metkar\Downloads\BTP Phase 2 dataset\Region 1\T47D.xlsx")

In [9]:
df4

loc1  loc2  loc3  loc4  loc5  loc6  loc7
0      1     1     0     1     1     0     1
1      1     1     0     1     0     0     0
2      1     0     0     1     0     0     1
3      1     1     0     1     0     0     1
4      0     0     0     1     1     0     0
5      1     0     0     0     0     0     1
6      0     0     0     0     0     0     1
7      1     0     1     0     0     0     1
8      1     1     0     1     0     0     0
9      1     0     1     0     0     0     1
10     0     0     0     0     0     0     1
11     1     0     0     1     0     0     1

In [10]:
df5=pd.read_excel(r"C:\Users\Siddhesh J. Metkar\Downloads\BTP Phase 2 dataset\Region 1\ZR-75-1.xlsx")

In [11]:
df5

loc1  loc2  loc3  loc4  loc5  loc6  loc7
0      0     0     0     0     0     0     0
1      1     0     0     0     0     0     0
2      1     1     1     1     1     0     0
3      1     0     1     1     1     0     0
4      0     0     0     0     0     0     0
5      0     0     0     1     0     0     0
6      1     1     1     1     1     1     1
7      0     0     0     0     0     0     0
8      1     0     0     1     0     0     1
9      0     0     1     1     1     1     0
10     1     1     1     1     1     0     1
11     0     0     0     0     0     0     0

# F-Test

### To check whether the variance of methylation on different loci are likely to be different or not.

### My NULL hypothesis was that Variances(of methylation) in different loci are equal and the ALTERNATE hypothesis was that variances in different loci are different.

### For p-values, less than 0.05 I rejected the Null hypothesis.

## For Region 1

In [12]:
from scipy.stats import chi2_contingency


In [13]:
import scipy.stats as stats
# stats f_oneway functions takes the groups as input and returns ANOVA F and p value
fvalue, pvalue = stats.f_oneway(df['loc1'], df['loc2'], df['loc3'], df['loc4'],df['loc5'],df['loc6'],df['loc7'])
print(fvalue)

5.574525745257451


In [14]:
print(pvalue)

7.661751166847006e-05


In [15]:
import scipy.stats as stats
# stats f_oneway functions takes the groups as input and returns ANOVA F and p value
fvalue, pvalue = stats.f_oneway(df2['loc1'], df2['loc2'], df2['loc3'], df2['loc4'],df2['loc5'],df2['loc6'],df2['loc7'])
print(fvalue)


4.663742690058479


In [16]:
print(pvalue)

0.00042825400477381766


In [17]:
import scipy.stats as stats
# stats f_oneway functions takes the groups as input and returns ANOVA F and p value
fvalue, pvalue = stats.f_oneway(df3['loc1'], df3['loc2'], df3['loc3'], df3['loc4'],df3['loc5'],df3['loc6'],df3['loc7'])
print(fvalue)
print(pvalue)

10.32456140350877
2.2846425937519788e-08


In [18]:
import scipy.stats as stats
# stats f_oneway functions takes the groups as input and returns ANOVA F and p value
fvalue, pvalue = stats.f_oneway(df4['loc1'], df4['loc2'], df4['loc3'], df4['loc4'],df4['loc5'],df4['loc6'],df4['loc7'])
print(fvalue)
print(pvalue)

6.331262939958589
1.9067105015184105e-05


In [19]:
import scipy.stats as stats
# stats f_oneway functions takes the groups as input and returns ANOVA F and p value
fvalue, pvalue = stats.f_oneway(df5['loc1'], df5['loc2'], df5['loc3'], df5['loc4'],df5['loc5'],df5['loc6'],df5['loc7'])
print(fvalue)
print(pvalue)

1.1767441860465115
0.32755892099713596


### To check variance of methylation across different cell lines for a particular loci.

In [63]:
import scipy.stats as stats
# stats f_oneway functions takes the groups as input and returns ANOVA F and p value
fvalue, pvalue = stats.f_oneway(df['loc1'], df2['loc1'], df3['loc1'],df4['loc1'],df5['loc1'])
print(fvalue)
print(pvalue)

3.6882352941176455
0.00989817027421042


In [64]:
import scipy.stats as stats
# stats f_oneway functions takes the groups as input and returns ANOVA F and p value
fvalue, pvalue = stats.f_oneway(df['loc2'], df2['loc2'], df3['loc2'],df4['loc2'],df5['loc2'])
print(fvalue)
print(pvalue)

4.916666666666664
0.0018411503521795348


In [65]:
import scipy.stats as stats
# stats f_oneway functions takes the groups as input and returns ANOVA F and p value
fvalue, pvalue = stats.f_oneway(df['loc3'], df2['loc3'], df3['loc3'],df4['loc3'],df5['loc3'])
print(fvalue)
print(pvalue)

14.071428571428573
5.706033794973738e-08


In [66]:
import scipy.stats as stats
# stats f_oneway functions takes the groups as input and returns ANOVA F and p value
fvalue, pvalue = stats.f_oneway(df['loc4'], df2['loc4'], df3['loc4'],df4['loc4'],df5['loc4'])
print(fvalue)
print(pvalue)

2.6481481481481493
0.04286918952065627


In [67]:
import scipy.stats as stats
# stats f_oneway functions takes the groups as input and returns ANOVA F and p value
fvalue, pvalue = stats.f_oneway(df['loc5'], df2['loc5'], df3['loc5'],df4['loc5'],df5['loc5'])
print(fvalue)
print(pvalue)

14.07142857142858
5.706033794973687e-08


In [68]:
import scipy.stats as stats
# stats f_oneway functions takes the groups as input and returns ANOVA F and p value
fvalue, pvalue = stats.f_oneway(df['loc6'], df2['loc6'], df3['loc6'],df4['loc6'],df5['loc6'])
print(fvalue)
print(pvalue)

2.391304347826087
0.06171188029566055


In [69]:
import scipy.stats as stats
# stats f_oneway functions takes the groups as input and returns ANOVA F and p value
fvalue, pvalue = stats.f_oneway(df['loc7'], df2['loc7'], df3['loc7'],df4['loc7'],df5['loc7'])
print(fvalue)
print(pvalue)

3.845864661654134
0.007948515627822469


## For Region 2

In [20]:
df6 = pd.read_excel(r"C:\Users\Siddhesh J. Metkar\Downloads\BTP Phase 2 dataset\Region 2\MCF-7.xlsx")

In [21]:
df6

loc1  loc2  loc3
0      0     1     0
1      0     0     0
2      0     0     0
3      0     0     0
4      0     0     0
5      0     0     0
6      0     1     1
7      0     0     1
8      0     0     0
9      0     0     0
10     0     0     0
11     0     0     0
12     0     0     0

In [22]:
df7 = pd.read_excel(r"C:\Users\Siddhesh J. Metkar\Downloads\BTP Phase 2 dataset\Region 2\MDA-MB-231.xlsx")

In [23]:
df7

loc1  loc2  loc3
0      0     1     1
1      0     0     0
2      0     1     1
3      1     1     1
4      0     1     1
5      0     0     0
6      0     1     1
7      0     0     0
8      0     0     0
9      0     1     1
10     0     1     1
11     0     0     0
12     0     1     1

In [24]:
df8 = pd.read_excel(r"C:\Users\Siddhesh J. Metkar\Downloads\BTP Phase 2 dataset\Region 2\MDA-MB-453.xlsx")

In [25]:
df8

loc1  loc2  loc3
0      1     1     1
1      1     1     1
2      1     1     1
3      0     1     1
4      1     1     1
5      1     1     1
6      1     1     1
7      0     1     1
8      1     1     1
9      0     0     0
10     0     1     1
11     1     1     1
12     0     0     0

In [26]:
df9 = pd.read_excel(r"C:\Users\Siddhesh J. Metkar\Downloads\BTP Phase 2 dataset\Region 2\T47D.xlsx")

In [27]:
df9

loc1  loc2  loc3
0      1     1     1
1      0     1     1
2      1     0     0
3      1     0     0
4      1     1     1
5      1     0     0
6      1     0     0
7      1     0     0
8      1     1     1
9      1     0     0
10     1     1     1
11     1     0     0
12     1     0     0

In [28]:
df10 = pd.read_excel(r"C:\Users\Siddhesh J. Metkar\Downloads\BTP Phase 2 dataset\Region 2\ZR-75-1.xlsx")

In [29]:
df10

loc1  loc2  loc3
0      0     0     0
1      0     0     0
2      0     0     0
3      0     0     0
4      0     0     0
5      0     1     1
6      0     0     0
7      0     0     0
8      0     1     1
9      0     0     0
10     0     0     0
11     0     1     1
12     0     0     0

In [30]:
import scipy.stats as stats
# stats f_oneway functions takes the groups as input and returns ANOVA F and p value
fvalue, pvalue = stats.f_oneway(df6['loc1'], df6['loc2'], df6['loc3'])
print(fvalue)
print(pvalue)

1.090909090909091
0.34675770465366773


In [31]:
import scipy.stats as stats
# stats f_oneway functions takes the groups as input and returns ANOVA F and p value
fvalue, pvalue = stats.f_oneway(df7['loc1'], df7['loc2'], df7['loc3'])
print(fvalue)
print(pvalue)

6.391304347826092
0.00421380697392216


In [32]:
import scipy.stats as stats
# stats f_oneway functions takes the groups as input and returns ANOVA F and p value
fvalue, pvalue = stats.f_oneway(df8['loc1'], df8['loc2'], df8['loc3'])
print(fvalue)
print(pvalue)

1.2857142857142865
0.28884308789923907


In [33]:
import scipy.stats as stats
# stats f_oneway functions takes the groups as input and returns ANOVA F and p value
fvalue, pvalue = stats.f_oneway(df9['loc1'], df9['loc2'], df9['loc3'])
print(fvalue)
print(pvalue)

6.391304347826092
0.00421380697392216


In [34]:
import scipy.stats as stats
# stats f_oneway functions takes the groups as input and returns ANOVA F and p value
fvalue, pvalue = stats.f_oneway(df10['loc1'], df10['loc2'], df10['loc3'])
print(fvalue)
print(pvalue)

1.7999999999999987
0.17985878990921414


### To check variance of methylation across different cell lines for a particular loci.

In [70]:
import scipy.stats as stats
# stats f_oneway functions takes the groups as input and returns ANOVA F and p value
fvalue, pvalue = stats.f_oneway(df6['loc1'], df7['loc1'], df8['loc1'],df9['loc1'],df10['loc1'])
print(fvalue)
print(pvalue)

28.312500000000007
3.150840466963921e-13


In [71]:
import scipy.stats as stats
# stats f_oneway functions takes the groups as input and returns ANOVA F and p value
fvalue, pvalue = stats.f_oneway(df6['loc2'], df7['loc2'], df8['loc2'],df9['loc2'],df10['loc2'])
print(fvalue)
print(pvalue)

5.337662337662337
0.0009589696065162119


In [72]:
import scipy.stats as stats
# stats f_oneway functions takes the groups as input and returns ANOVA F and p value
fvalue, pvalue = stats.f_oneway(df6['loc3'], df7['loc3'], df8['loc3'],df9['loc3'],df10['loc3'])
print(fvalue)
print(pvalue)

5.337662337662335
0.0009589696065162119


## Results of F-test:

### For Region-1, All except ZR-75-1 have different variance in methylation in different loci.
### For Region-2, MDA-MB-231, T47D have different variance in methylation in different loci.




# Z-Test

### A two proportion z-test allows you to compare two proportions to see if they are the same. The null hypothesis (H0) for the test is that the proportions are the same. The alternate hypothesis (H1) is that the proportions are not the same.

### If the p-value is less than 0.05 then null hypothesis(H0) is rejected.

In [35]:
import numpy as np
from statsmodels.stats.proportion import proportions_ztest
count = np.array([5, 12])
nobs = np.array([12, 12])
stat, pval = proportions_ztest(count, nobs)
print('{0:0.3f}'.format(pval))

0.002


In [36]:
def Z_Test(d1,d2):
    p1=(d1.values==1).sum()
    p2=(d2.values==1).sum()
    n1=len(d1)*d1.shape[1]
    n2=len(d2)*d2.shape[1]
    #p= (p1+p2)/(n1+n2)
    #p_hat = p*(1-p)*((1/n1)+(1/n2))
    count = np.array([p1, p2])
    nobs = np.array([n1, n2])
    stat, pval = proportions_ztest(count, nobs)
    
    print('P-Value is {0:0.3f}'.format(pval))
    print('Z-Value is {0:0.3f}'.format(stat))
    print(" ")
    print(" ")

In [37]:
Z_Test(df,df2)  # Z-Test for Region 1 in Cell lines MCF-7 and MDA-MB-453

P-Value is 0.569
Z-Value is -0.570
 
 


In [38]:
Z_Test(df2,df3)  # Z-Test for Region 1 in Cell lines MDA-MB-453 and MDA-MB-231

P-Value is 0.147
Z-Value is 1.449
 
 


In [39]:
Z_Test(df3,df4)  # Z-Test for Region 1 in Cell lines  MDA-MB-231 and T47D

P-Value is 0.000
Z-Value is 4.190
 
 


In [40]:
Z_Test(df4,df5)  # Z-Test for Region 1 in Cell lines T47D and ZR-75-1

P-Value is 0.751
Z-Value is 0.318
 
 


In [41]:
Z_Test(df,df3)  # Z-Test for Region 1 in Cell lines MCF-7 and MDA-MB-231

P-Value is 0.377
Z-Value is 0.884
 
 


In [42]:
Z_Test(df,df4)  # Z-Test for Region 1 in Cell lines MCF-7 and T47D

P-Value is 0.000
Z-Value is 5.008
 
 


In [43]:
Z_Test(df,df5)  # Z-Test for Region 1 in Cell lines MCF-7 and ZR-75-1

P-Value is 0.000
Z-Value is 5.301
 
 


In [44]:
Z_Test(df2,df4)  # Z-Test for Region 1 in Cell lines MDA-MB-453 and T47D

P-Value is 0.000
Z-Value is 5.515
 
 


In [45]:
Z_Test(df2,df5)  # Z-Test for Region 1 in Cell lines MDA-MB-453 and ZR-75-1

P-Value is 0.000
Z-Value is 5.802
 
 


In [46]:
Z_Test(df3,df5)  # Z-Test for Region 1 in Cell lines MDA-MB-231 and ZR-75-1

P-Value is 0.000
Z-Value is 4.490
 
 


In [47]:
Z_Test(df6,df7)  # Z-Test for Region 2 in Cell lines MCF-7 and MDA-MB-231

P-Value is 0.001
Z-Value is -3.319
 
 


In [48]:
Z_Test(df6,df8)  # Z-Test for Region 2 in Cell lines MCF-7 and MDA-MB-453

P-Value is 0.000
Z-Value is -5.937
 
 


In [49]:
Z_Test(df6,df9)  # Z-Test for Region 2 in Cell lines MCF-7 and T47D

P-Value is 0.000
Z-Value is -4.323
 
 


In [50]:
Z_Test(df6,df10)  # Z-Test for Region 2 in Cell lines MCF-7 and ZR-75-1

P-Value is 0.498
Z-Value is -0.677
 
 


In [51]:
Z_Test(df7,df8)  # Z-Test for Region 2 in Cell lines MDA-MB-231 and MDA-MB-453

P-Value is 0.003
Z-Value is -3.008
 
 


In [52]:
Z_Test(df7,df9)  # Z-Test for Region 2 in Cell lines MDA-MB-231 and T47D

P-Value is 0.258
Z-Value is -1.132
 
 


In [53]:
Z_Test(df7,df10)  # Z-Test for Region 2 in Cell lines MDA-MB-231 and ZR-75-1

P-Value is 0.006
Z-Value is 2.731
 
 


In [54]:
Z_Test(df8,df9)  # Z-Test for Region 2 in Cell lines MDA-MB-453 and T47D

P-Value is 0.055
Z-Value is 1.922
 
 


In [55]:
Z_Test(df8,df10)  # Z-Test for Region 2 in Cell lines MDA-MB-453 and ZR-75-1

P-Value is 0.000
Z-Value is 5.451
 
 


In [56]:
Z_Test(df9,df10)  # Z-Test for Region 2 in Cell lines T47D and ZR-75-1

P-Value is 0.000
Z-Value is 3.777
 
 


# CHI - Squared Test 

### Null Hypothesis: There is no relation between count of methylated and count of unmethylated sites. If you know the value of one variable, it does not help you predict the value of another variable.

### Alternate Hypothesis: There is a relation between count of methylated and count of unmethylated sites. If you know the value of one variable, it helps you predict the value of another variable.

### For Region 1

In [57]:
from scipy.stats import chi2_contingency
from scipy.stats import chi2

# contingency table
table = [[31,64,33,60,68],[53,20,51,24,16]]   # [[total mehylation count of all the cell lines],[total unmehylation count of all the cell lines]]
print(table)
stat, p, dof, expected = chi2_contingency(table)
print('dof=%d' % dof)
print(expected)
print(" ")

# interpret test-statistic
prob = 0.95
critical = chi2.ppf(prob, dof)
print('probability=%.3f, critical=%.3f, stat=%.3f' % (prob, critical, stat))
if abs(stat) >= critical:
	print('Dependent (reject H0)')
else:
	print('Independent (fail to reject H0)')
print(" ")
    
# interpret p-value
alpha = 1.0 - prob
print('significance=%.3f, p=%.3f' % (alpha, p))
if p <= alpha:
	print('Dependent (reject H0)')
else:
	print('Independent (fail to reject H0)')
print(" ")

[[31, 64, 33, 60, 68], [53, 20, 51, 24, 16]]
dof=4
[[51.2 51.2 51.2 51.2 51.2]
 [32.8 32.8 32.8 32.8 32.8]]
 
probability=0.950, critical=9.488, stat=63.164
Dependent (reject H0)
 
significance=0.050, p=0.000
Dependent (reject H0)
 


### For Region 2

In [58]:
from scipy.stats import chi2_contingency
from scipy.stats import chi2

# contingency table
table2 = [[6,4,22,17,30],[33,35,17,22,9]] # [[total mehylation count of all the cell lines],[total unmehylation count of all the cell lines]]
print(table2)
stat, p, dof, expected = chi2_contingency(table2)
print('dof=%d' % dof)
print(expected)
print(" ")

# interpret test-statistic
prob = 0.95
critical = chi2.ppf(prob, dof)
print('probability=%.3f, critical=%.3f, stat=%.3f' % (prob, critical, stat))
if abs(stat) >= critical:
	print('Dependent (reject H0)')
else:
	print('Independent (fail to reject H0)')
print(" ")

# interpret p-value
alpha = 1.0 - prob
print('significance=%.3f, p=%.3f' % (alpha, p))
if p <= alpha:
	print('Dependent (reject H0)')
else:
	print('Independent (fail to reject H0)')
print(" ")


[[6, 4, 22, 17, 30], [33, 35, 17, 22, 9]]
dof=4
[[15.8 15.8 15.8 15.8 15.8]
 [23.2 23.2 23.2 23.2 23.2]]
 
probability=0.950, critical=9.488, stat=50.729
Dependent (reject H0)
 
significance=0.050, p=0.000
Dependent (reject H0)
 


# T-test

In [59]:
from scipy.stats import ttest_ind

def t_test(df,df2,df3,df4,df5,df6,df7,df8,df9,df10):
        p1=(df.values==1).sum()
        p2=(df2.values==1).sum()
        p3=(df3.values==1).sum()
        p4=(df4.values==1).sum()
        p5=(df5.values==1).sum()
        
        q1=(df6.values==1).sum()
        q2=(df7.values==1).sum()
        q3=(df8.values==1).sum()
        q4=(df9.values==1).sum()
        q5=(df10.values==1).sum()
        
        stat , p = ttest_ind([p1,p2,p3,p4,p5],[q1,q2,q3,q4,q5])
        print('T-Value is {0:0.3f}'.format(stat))
        print('P-Value is {0:0.3f}'.format(p))
    

In [60]:
t_test(df,df2,df3,df4,df5,df6,df7,df8,df9,df10)

T-Value is 3.789
P-Value is 0.005


# Welch T-test

In [61]:
def welch_t_test(df,df2,df3,df4,df5,df6,df7,df8,df9,df10):
        p1=(df.values==1).sum()
        p2=(df2.values==1).sum()
        p3=(df3.values==1).sum()
        p4=(df4.values==1).sum()
        p5=(df5.values==1).sum()
        
        q1=(df6.values==1).sum()
        q2=(df7.values==1).sum()
        q3=(df8.values==1).sum()
        q4=(df9.values==1).sum()
        q5=(df10.values==1).sum()
        
        stat , p = ttest_ind([p1,p2,p3,p4,p5],[q1,q2,q3,q4,q5],equal_var=False)
        print('T-Value is {0:0.3f}'.format(stat))
        print('P-Value is {0:0.3f}'.format(p))

In [62]:
welch_t_test(df,df2,df3,df4,df5,df6,df7,df8,df9,df10)

T-Value is 3.789
P-Value is 0.008
